Replication should now work from PG 16 Standbys (#858)
I tried PeerDB on Read Replicas in PG 16:
1. Initial Load worked as expected
2. SyncFlows were erroring out:
```
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
```
The reason was `pg_current_wal_lsn()` cannot be run on a standby. I
changed that function to `pg_last_wal_replay_lsn()` if Replica.

For now `CREATE PUBLICATION` needs to be run on primary by user

Co-authored-by: Philip Dubé <philip@peerdb.io>