QRep: Add test for no rows mirror (#1396)
Adds a test for syncing an empty table via QRep. 
This PR is to address [this
comment](https://github.com/PeerDB-io/peerdb/pull/1393#issuecomment-1968746921)

The test successfully caught the error which was seen
[pre-patch](#1393):
```
        qrep_flow_pg_test.go:340: 
                Error Trace: peerdb/flow/e2e/postgres/qrep_flow_pg_test.go:340
                Error:          Received unexpected error:
                                workflow execution error (type: QRepFlowWorkflow, workflowID: default-test-workflow-id, runID: default-test-run-id): 
runtime error: integer divide by zero
```