Parameter for cdc with only snapshot (#884)
This PR introduces a parameter - `initial_copy_only` which when set,
will initiate CDC and exit after Snapshot Flow is complete. No Sync
Flows will be called. By default this is set to false.

<img width="1089" alt="Screenshot 2023-12-22 at 10 15 30 PM"
src="https://github.com/PeerDB-io/peerdb/assets/65964360/99296169-7dfb-425f-bb9a-6dcddb3182f5">

In the UI, this parameter is listed in the Advanced Settings section:
<img width="1195" alt="Screenshot 2023-12-22 at 10 51 13 PM"
src="https://github.com/PeerDB-io/peerdb/assets/65964360/ae6f5b2a-c637-495d-9451-a205934ad163">

Validation for this parameter is set in both query layer and UI:
```bash
amogh=> CREATE MIRROR sfnosnappy1                                                                                                                                                                                                              
amogh-> FROM postgres_local TO sf_peer
amogh-> WITH TABLE MAPPING (
amogh(> public.oss2:public.oss2nexusso6,
amogh(> public.oss2ud1:public.oss2ud1nexusso6
amogh(> )
amogh-> WITH(
amogh(> do_initial_copy = false,
amogh(> snapshot_staging_path = '',
amogh(> initial_copy_only = true
amogh(> );
ERROR:  initial_copy_only is set to true, but do_initial_copy is set to false
```

<img width="997" alt="Screenshot 2023-12-22 at 10 57 46 PM"
src="https://github.com/PeerDB-io/peerdb/assets/65964360/e1d83b9f-49a8-4951-ab69-5826e242bf38">

This has been tested via UI and query layer and the happy path where it
is not set it also tested.