fix(mongo): update retry change stream tests to SourceTableMapping
TestRetryChangeStreamErrorRecovery and TestRetryChangeStreamRecoveriesAreBounded
(#4841) still build their TableNameMapping as map[string]model.NameAndExclude,
which #4818 renamed to model.SourceTableMapping. main currently fails to compile
the mongo test package:

    vet: connectors/mongo/cdc_test.go:373:44: undefined: model.NameAndExclude

Drop this commit if it is fixed upstream first.