HStore Support for BigQuery (#995)
Maps HStore to JSON in BigQuery. 
Achieves this by transforming `'"a"=>"b"'` to `{"a":"b"}` via string
functions, in both qrep/initial load and cdc
Test added

Relies on the fact hstore key and value must be quoted strings (although
the key can be empty and this case is supported)
And follows the syntax in the example above

```sql
postgres=# select 'a'::hstore;
ERROR:  Unexpected end of string
LINE 1: select 'a'::hstore;
               ^
postgres=# select 'a=>b'::hstore;
-[ RECORD 1 ]----
hstore | "a"=>"b"

postgres=# select 'a=>'::hstore;
ERROR:  Unexpected end of string
LINE 1: select 'a=>'::hstore;

postgres=# select 'a=>3434'::hstore;
-[ RECORD 1 ]-------
hstore | "a"=>"3434"
```